In [4]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
path = "/Users/siqiliu/Desktop/Teaching/Suwei/Tommy/Data/Nal Dispensing Rate/State Naloxone Dispensing Rates.csv"
df = pd.read_csv(path, skiprows=0)

In [3]:
tb = df.pivot(index='STATE_ABBREV', columns='YEAR', values='naloxone_dispensing_rate')
tb = tb.reindex(df['STATE_ABBREV'].unique())
state_ab=df['STATE_ABBREV']
tb.head()

YEAR          2019  2020  2021  2022  2023
STATE_ABBREV
AL             0.2   0.2   0.3   0.3   0.4
AK             0.2   0.2   0.2   0.4   0.5
AZ             0.4   0.5   0.6   0.7   0.7
AR             0.1   0.2   0.8   1.7   1.9
CA             0.5   0.4   0.4   0.6   0.7

In [8]:
data_format1 = "/Users/siqiliu/Desktop/Teaching/Suwei/Tommy/Data/Census Eco Indicators/S1501 Education/ACSST5Y{year}.S1501-Data.csv"
data_format2 = "/Users/siqiliu/Desktop/Teaching/Suwei/Tommy/Data/Census Eco Indicators/S1701 Poverty level/ACSST5Y{year}.S1701-Data.csv"
data_format3 = "/Users/siqiliu/Desktop/Teaching/Suwei/Tommy/Data/Census Eco Indicators/S1901 Household income/ACSST5Y{year}.S1901-Data.csv"
data_format4 = "/Users/siqiliu/Desktop/Teaching/Suwei/Tommy/Data/Census Eco Indicators/S2301 Unemp rate/ACSST5Y{year}.S2301-Data.csv"

In [33]:
cl_list = []
for year in range(2010, 2024):
    data1 = pd.read_csv(data_format1.format(year=year), skiprows=0)
    df = data1.iloc[1:51,2:].copy()
    df.index = data1.iloc[1:51,1]
    df = df.dropna(axis=1, how='all')
    df = df.loc[:, df.ne("(X)").any()]
    cl = pd.DataFrame(index = df.columns, columns = [year], data = np.ones(df.shape[1]))
    cl_list.append(cl)
    print(f"Year: {year}, Education Data Shape: {df.shape}")

Year: 2010, Education Data Shape: (50, 224)
Year: 2011, Education Data Shape: (50, 223)
Year: 2012, Education Data Shape: (50, 223)
Year: 2013, Education Data Shape: (50, 223)
Year: 2014, Education Data Shape: (50, 223)
Year: 2015, Education Data Shape: (50, 606)
Year: 2016, Education Data Shape: (50, 606)
Year: 2017, Education Data Shape: (50, 606)
Year: 2018, Education Data Shape: (50, 610)
Year: 2019, Education Data Shape: (50, 618)
Year: 2020, Education Data Shape: (50, 618)
Year: 2021, Education Data Shape: (50, 618)
Year: 2022, Education Data Shape: (50, 618)
Year: 2023, Education Data Shape: (50, 618)

In [34]:
result = cl_list[0]
for i in range(1, len(cl_list)):
    result = result.join(cl_list[i], how='outer')

In [38]:
common = result.dropna(axis=0, how='any')

In [41]:
print(len(common))

195

In [51]:
common.head(100)

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
S1501_C01_001E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_001M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_002E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_002M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_003E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_003M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_004E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_004M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_005E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_005M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_006E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_006M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_007E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_007M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_008E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_008M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_009E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_009M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_010E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_010M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_011E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_011M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_012E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_012M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_013E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_013M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_016E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_016M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_017E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_017M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_018E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_018M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_019E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_019M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_020E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_020M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_021E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_021M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_022E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_022M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_023E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_023M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_024E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_024M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_025E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_025M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_026E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_026M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_027E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_027M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_028E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_028M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_029E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_029M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_030E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_030M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_031E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_031M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_032E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_032M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_033E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_033M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_034E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_034M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_035E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_035M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_036E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_036M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_037E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_037M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C01_038E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_002E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_002M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_003E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_003M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_004E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_004M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_005E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_005M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_007E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_007M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_008E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_008M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_009E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_009M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_010E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_010M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_011E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_011M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_012E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_012M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_013E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_013M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_014E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_014M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_015E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_015M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_017E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_017M,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
S1501_C02_018E,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [87]:
meta = "/Users/siqiliu/Desktop/Teaching/Suwei/Tommy/Data/Census Eco Indicators/S1501 Education/ACSST5Y{year}.S1501-Column-Metadata.csv"
year = 2023
meta_data = pd.read_csv(meta.format(year=year), skiprows=0)
mask = meta_data['Column Name'].str.startswith('S1501_C01_') & meta_data['Column Name'].str.endswith('E')
meta_data = meta_data[mask].copy().reset_index(drop=True)
meta_data['Label'] = meta_data['Label'].str.split('!!').str[2:]

In [88]:
for i in range(len(meta_data)):
    print(meta_data.iloc[i,1])

['AGE BY EDUCATIONAL ATTAINMENT', 'Population 18 to 24 years']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 18 to 24 years', 'Less than high school graduate']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 18 to 24 years', 'High school graduate (includes equivalency)']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 18 to 24 years', "Some college or associate's degree"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 18 to 24 years', "Bachelor's degree or higher"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', 'Less than 9th grade']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', '9th to 12th grade, no diploma']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', 'High school graduate (includes equivalency)']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', 'Some college, no degree']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', "Associate's degree"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', "Bachelor's degree"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', 'Graduate or professional degree']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', 'High school graduate or higher']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 years and over', "Bachelor's degree or higher"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 to 34 years']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 to 34 years', 'High school graduate or higher']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 25 to 34 years', "Bachelor's degree or higher"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 35 to 44 years']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 35 to 44 years', 'High school graduate or higher']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 35 to 44 years', "Bachelor's degree or higher"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 45 to 64 years']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 45 to 64 years', 'High school graduate or higher']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 45 to 64 years', "Bachelor's degree or higher"]
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 65 years and over']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 65 years and over', 'High school graduate or higher']
['AGE BY EDUCATIONAL ATTAINMENT', 'Population 65 years and over', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'White alone']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'White alone', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'White alone', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'White alone, not Hispanic or Latino']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'White alone, not Hispanic or Latino', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'White alone, not Hispanic or Latino', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Black alone']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Black alone', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Black alone', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'American Indian or Alaska Native alone']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'American Indian or Alaska Native alone', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'American Indian or Alaska Native alone', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Asian alone']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Asian alone', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Asian alone', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Native Hawaiian and Other Pacific Islander alone']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Native Hawaiian and Other Pacific Islander alone', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Native Hawaiian and Other Pacific Islander alone', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Some other race alone']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Some other race alone', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Some other race alone', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Two or more races']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Two or more races', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Two or more races', "Bachelor's degree or higher"]
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Hispanic or Latino Origin']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Hispanic or Latino Origin', 'High school graduate or higher']
['RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT', 'Hispanic or Latino Origin', "Bachelor's degree or higher"]
['POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL', 'Less than high school graduate']
['POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL', 'High school graduate (includes equivalency)']
['POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL', "Some college or associate's degree"]
['POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL', "Bachelor's degree or higher"]
['MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2023 INFLATION-ADJUSTED DOLLARS)', 'Population 25 years and over with earnings']
['MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2023 INFLATION-ADJUSTED DOLLARS)', 'Population 25 years and over with earnings', 'Less than high school graduate']
['MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2023 INFLATION-ADJUSTED DOLLARS)', 'Population 25 years and over with earnings', 'High school graduate (includes equivalency)']
['MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2023 INFLATION-ADJUSTED DOLLARS)', 'Population 25 years and over with earnings', "Some college or associate's degree"]
['MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2023 INFLATION-ADJUSTED DOLLARS)', 'Population 25 years and over with earnings', "Bachelor's degree"]
['MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2023 INFLATION-ADJUSTED DOLLARS)', 'Population 25 years and over with earnings', 'Graduate or professional degree']